### ISSUE TITLE
NameError: name 'CannotConfigureRigError' is not defined

### ISSUE THREAD

**Issue by bostrt** [TurboTurtle/rig#17]
Receiving exception while trying to list current rigs:

```
$ git rev-parse HEAD
baedc300174197dddee80e421e5b0aa343e4f45a
$ sudo python3 ./rig list
Traceback (most recent call last):
  File "./rig", line 56, in <module>
    ret = rig.execute()
  File "/home/rbost/code/rig/rigging/__init__.py", line 112, in execute
    self.list_rigs()
  File "/home/rbost/code/rig/rigging/__init__.py", line 178, in list_rigs
    socks = os.listdir('/var/run/rig')
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/rig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./rig", line 60, in <module>
    except CannotConfigureRigError:
NameError: name 'CannotConfigureRigError' is not defined
````

**Comment by bostrt** [comment]
This is because I didn't have any running rigs.

**Comment by TurboTurtle** [comment]
The `FileNotFoundError` should be avoidable via packaging (e.g. making sure /var/run/rig is created at install time), but it is interesting that we get a `NameError` like that.

I'll make a note to look into this early next week, I'm on PTO this week but I have a general idea of what might be behind this.
