### ISSUE TITLE
[rig] cannot resolve the package dependency to python3-psutil

### ISSUE THREAD

**Issue by mmatsuya** [TurboTurtle/rig#25]
python3-psutil was not installed automatically as the dependency for rig package on RHEL8.

```
# rig --help
Traceback (most recent call last):
  File "/usr/bin/rig", line 67, in <module>
    supported_rigs = _load_supported_rigs()
  File "/usr/bin/rig", line 59, in _load_supported_rigs
    modules.extend(_import_modules(_mod))
  File "/usr/bin/rig", line 26, in _import_modules
    module = __import__(modname, globals(), locals(), [mod_short_name])
  File "/usr/lib/python3.6/site-packages/rigging/rigs/process.py", line 16, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**Comment by TurboTurtle** [comment]
Ah, this comes from a schism in Fedora and RHEL build processes where Fedora auto--determines the requirements. Easy enough fix to add the Requires to the RHEL specfile.
